# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Munsel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Munsel
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  

  platform :ios, '9.0'
  target 'MunselTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Munsel-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Munsel-tvOS

  target 'Munsel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
